// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsUJzZyK__nsrkJcXwArkV8Ol1E0xjDnA',
    appId: '1:9578384434:web:6ed94d471279daf54cc02b',
    messagingSenderId: '9578384434',
    projectId: 'chatbot-609bd',
    authDomain: 'chatbot-609bd.firebaseapp.com',
    storageBucket: 'chatbot-609bd.firebasestorage.app',
    measurementId: 'G-SBDZ0JBNGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvi7bgwkXwiSmIhz76wDU-LncKoT1qD74',
    appId: '1:9578384434:android:7781c3446d8d959d4cc02b',
    messagingSenderId: '9578384434',
    projectId: 'chatbot-609bd',
    storageBucket: 'chatbot-609bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBauUAB9r4IEuQjcb4ulpqGzHKD1no9_o0',
    appId: '1:9578384434:ios:2e452f4f61edd4be4cc02b',
    messagingSenderId: '9578384434',
    projectId: 'chatbot-609bd',
    storageBucket: 'chatbot-609bd.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBauUAB9r4IEuQjcb4ulpqGzHKD1no9_o0',
    appId: '1:9578384434:ios:2e452f4f61edd4be4cc02b',
    messagingSenderId: '9578384434',
    projectId: 'chatbot-609bd',
    storageBucket: 'chatbot-609bd.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsUJzZyK__nsrkJcXwArkV8Ol1E0xjDnA',
    appId: '1:9578384434:web:a2388a510883117e4cc02b',
    messagingSenderId: '9578384434',
    projectId: 'chatbot-609bd',
    authDomain: 'chatbot-609bd.firebaseapp.com',
    storageBucket: 'chatbot-609bd.firebasestorage.app',
    measurementId: 'G-P5CNP5TPNZ',
  );
}
